services:
  sftp:
    container_name: sftp
    image: atmoz/sftp:latest
    restart: no
    attach: false
    command: example:1234:::upload
    networks:
      - app
  database:
    container_name: database
    image: mongo:latest
    restart: no
    attach: false
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: test
    volumes:
      - ./tests/mongodb-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - app
  app:
    container_name: app
    restart: no
    build:
      context: .
    environment:
      DB_SERVER: database
      DB_USERNAME: root
      DB_PASSWORD: 1234
      BACKUP_TYPE: local
      # BACKUP_TYPE: sftp
      # BACKUP_SFTP_HOST: sftp
      # BACKUP_SFTP_USERNAME: example
      # BACKUP_SFTP_PASSWORD: 1234
    networks:
      - app
    depends_on:
      - sftp
      - database

networks:
  app:
